### PR TITLE
Task-3: AWS Lambda

### PR DESCRIPTION
**Pull request by kotmatpockuh**
1. What was done? 
   Services are implemented (both: FE & BE)
   Additional scope - _Async/await, ES6 Modules, Webpack, SWAGGER, Unit Tests, Separated Codebase, Basic Error Handlers_.
2. Link to product-service API - https://c317st8p5i.execute-api.eu-west-1.amazonaws.com/dev/products
  FE: https://d30bubs8r0efun.cloudfront.net/ 
3. LInk to FE MR: https://github.com/kotmatpockuh/nodejs-aws-fe/pull/2
4. SWAGGER link: https://app.swaggerhub.com/apis-docs/kot_matpockuh/AWS-CarShop/1.0.0
5. Done 31.10.2020 / deadline 01.11.2020.
6. Score: 11 / 11.

### CODE REVIEW

**Comment by Max-Korsakov** [comment]
10 points. Async await functionality doesn't provided

**Comment by kotmatpockuh** [comment]
@Max-Korsakov I won't agree :)

1) https://github.com/kotmatpockuh/rs-school-aws-be/pull/1/files#diff-958056e41f4248ed2eea702022f66c397618f204b3b7057368a1a8ef111e9ae2R8

2) https://github.com/kotmatpockuh/rs-school-aws-be/pull/1/files#diff-e4af4773f795358b3c89dec316159b30ba12a46c89a1865f881fd1cab629ec89R37

3) https://github.com/kotmatpockuh/rs-school-aws-be/pull/1/files#diff-958056e41f4248ed2eea702022f66c397618f204b3b7057368a1a8ef111e9ae2R8

moreover, it was said in QA session: dummy weather call is more than enough (shown in my example, is commented not to output unnecessary data to FE).

For the future: please contact dev first.

**Comment by Max-Korsakov** [comment]
Yes, I've seen commented code, but without real implementation, I could not able to check if it works. If you'll add this code to you lambdas and I will check it, I'll change the mark. Add some delay to data fetching.

**Comment by kotmatpockuh** [comment]
@Max-Korsakov well... Check please video: https://www.youtube.com/watch?v=5ymuKq_RpZQ&feature=youtu.be&t=1850&ab_channel=TheRollingScopes

moreover: there is a real async example (handler)

**Comment by Max-Korsakov** [comment]
I've changed the mark. But I really don't understand why do you prefer to do all that unnecessary stuff and comment it instead of implementing real async data fetching and then just change your function to database handler.

**Comment by kotmatpockuh** [comment]
Thanks, @Max-Korsakov 
Why? Just because it was said so during QA. And atm I see no reason to uncomment dummy code.

**Comment by Max-Korsakov** [comment]
No. I mean you will do async requests to the database anyway.  Why you didn't implement that functionality with your current data (imitate async request with a promise and fetch your mock data) to not write it from scratch later and use existing functionality?

**Pull request merged**
